# Generated by Django 3.2.13 on 2022-06-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('intruder', 'Intruder')], max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='alert/images/')),
            ],
        ),
    ]
