# Generated by Django 3.2.13 on 2022-12-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_device_unit_id'),
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_log',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.local_server'),
        ),
        migrations.AddField(
            model_name='error_log',
            name='type',
            field=models.CharField(choices=[('socket', 'Socket'), ('server', 'Server'), ('local server', 'Local server'), ('remote server', 'Remote server'), ('stream', 'Stream')], default='socket', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='error_log',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
