# Generated by Django 3.2.13 on 2022-06-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cam', 'Cam'), ('lock', 'Lock')], max_length=50)),
                ('ip_address', models.CharField(max_length=15)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='local_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('name', models.CharField(default='Main', max_length=100)),
            ],
        ),
    ]
