# Generated by Django 3.2.13 on 2022-06-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_server',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household'),
        ),
        migrations.AddField(
            model_name='device',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.household'),
        ),
        migrations.AddField(
            model_name='device',
            name='pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devices.device'),
        ),
    ]
