# Generated by Django 3.2.13 on 2022-07-22 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_custom_profile_household'),
        ('devices', '0004_rename_device_passcodes_device_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household'),
        ),
    ]
