# Generated by Django 3.2.13 on 2022-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_server',
            name='unit_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
