# Generated by Django 3.2.13 on 2022-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_local_server_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_server',
            name='unit_id',
            field=models.CharField(max_length=1000),
        ),
    ]
