# Generated by Django 3.2.13 on 2022-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_local_server_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit_id',
            field=models.CharField(max_length=1000),
        ),
    ]
