# Generated by Django 3.2.13 on 2022-06-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_custom_profile_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_profile',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household'),
        ),
    ]
