# Generated by Django 3.2.13 on 2022-07-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_custom_profile_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowed_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='allowed-persons/')),
            ],
        ),
    ]
