# Generated by Django 3.2.13 on 2022-07-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_allowed_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_person',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.household'),
            preserve_default=False,
        ),
    ]
