# Generated by Django 3.2.13 on 2022-07-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_allowed_person_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_person',
            name='pic',
            field=models.ImageField(upload_to='static/allowed-persons/'),
        ),
    ]
